rendering:
  depth_output: true
  segmentation_output: true
  camera_type: "PERSP"
  render_engine: CYCLES
  denoise: true
  sampling_render: 2048
  resolution_x: 720
  resolution_y: 720
base_mesh:
  meshes: ["../moon_data/pgda/NPB/piece_0_1.tif", "../moon_data/pgda/NPB/piece_0_2.tif", "../moon_data/pgda/NPB/piece_0_3.tif"]
  material: "moon_albedo"
name: "ortho_nominal"
output:
  save_blender_file: true
  output_root: "tmp/datasets/"
terrain:
  desired_spatial_resolution: 1.0
  samples: 3
  rock_field:
    rock_source: 'assets/rocks/generated_100verts'
    h_min: 1.0
    h_max: 10.0
    density:
      type: "uniform"
      min: 0.06
      max: 0.10
  crater_field:
    crater_type: "normal"
    h_min: 1.0
    h_max: 30.0
    density:
      type: "uniform"
      min: 1.0
      max: 1.3
rendering_cases:
  cases: 10
  distributions:
    sun/elevation:
      type: "uniform"
      min: 0.1
      max: 0.2
    sun/azimuth:
      type: "uniform"
      min: 0.0
      max: 6.28
    camera/z:
      type: "uniform"
      min: 100
      max: 200