rendering:
  depth_output: false
  segmentation_output: true
  camera_type: "PERSP"
  render_engine: CYCLES
  denoise: true
  sampling_render: 2048
  resolution_x: 720
  resolution_y: 720
base_mesh:
  meshes: ["../moon_data/new_pgda78/Haworth_final_adj_5mpp_surf/Haworth_final_adj_5mpp_surf_piece_13_12.tif" ]
output:
  save_blender_file: false
  add_rendering_cases_blender: false
  output_root: "tmp/datasets/"
terrain:
  desired_spatial_resolution: 0.3
  samples: 2
  mesh_material: "Regolith7_MAT"
  rock_field:
    rock_source: 'rocks/generated_1000verts'
    h_min: 0.1
    h_max: 10.0
    density:
      type: "uniform"
      min: 0.03
      max: 0.04
  crater_field:
    crater_type: "normal"
    h_min: 0.6
    h_max: 30.0
    density:
      type: "uniform"
      min: 1.0
      max: 1.6
rendering_cases:
  cases: 10
  distributions:
    sun/elevation:
      type: "uniform"
      min: 0.1
      max: 0.2
    sun/azimuth:
      type: "uniform"
      min: 0.0
      max: 6.28
    camera/z:
      type: "uniform"
      min: 10
      max: 400