cases: 4
depth_output: true
segmentation_output: true
render_distributions:
  camera/x:
    type: "grid"
    min: -100.0
    max: 100.0
    n_values: 4
  camera/y:
    type: "grid"
    min: -100.0
    max: 100.0
    n_values: 6
  camera/z:
    type: "grid"
    min: 80
    max: 100.0
    n_values: 3
  camera/pitch:
    type: "uniform"
    min: -1.6
    max: -1.4
  camera/yaw:
    type: "uniform"
    min: 3.14
    max: 3.16
  sun/elevation:
    type: "uniform"
    min: 0.1
    max: 0.3
  sun/azimuth:
    type: "uniform"
    min: 0.0
    max: 6.28