cases: 100
depth_output: true
segmentation_output: true
render_distributions:
  camera/x:
    type: "fixed"
    value: 0.0
  camera/y:
    type: "fixed"
    value: 0.0
  camera/z:
    type: "uniform"
    min: 100.0
    max: 200.0
  camera/pitch:
    type: "uniform"
    min: -0.7
    max: -1.2
  camera/yaw:
    type: "uniform"
    min: 0.0
    max: 6.28
  sun/elevation:
    type: "uniform"
    min: 0.1
    max: 0.4
  sun/azimuth:
    type: "uniform"
    min: 0.0
    max: 6.28